version: "3.11"

services:
  core_api:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        BENCHLING_API_KEY: ${BENCHLING_API_KEY}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: core_api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    ports:
      - 5002:5000
    environment:
      PYTHONUNBUFFERED: 0
      PYTHONUTF8: 1
    volumes:
      - .:/usr/src/core-services-api
  